### PR TITLE
added changes for uploading the compliance file

### PR DESCRIPTION
**Pull request by AnikaAgiwal2711**
# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1283|

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X] I have verified that new and existing unit tests pass locally with my changes
- [X] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Backward compatibility is not broken

# How Has This Been Tested?
I've written Integration tests to test my changes

### CODE REVIEW

**Comment by AnikaAgiwal2711** [comment]
image

**Comment by AnikaAgiwal2711** [comment]
image

**Review by AkshaySainiDell — APPROVED** [review]
lgtm

**Review by Krunal-Thakkar — APPROVED** [review]

**Comment by AnikaAgiwal2711** [comment]
> @AnikaAgiwal2711 , Is there any github issue associated with this PR? How about adding copyright info all newly created files? // Copyright © 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
> 
> Thanks

I've a JIRA ticket. Not a github issue

**Comment by AnikaAgiwal2711** [comment]
Github issue : https://github.com/dell/csm/issues/1283

**Comment by AnikaAgiwal2711** [comment]
Done with all the changes

**Review by adarsh-dell — APPROVED** [review]
LGTM. Thanks @AnikaAgiwal2711

**Pull request merged**
