### PR TITLE
added snapshot policy changes

### PR DESCRIPTION
**Pull request by AnikaAgiwal2711**
# Description
Added functionalities for adding, modifying and removing snapshot policy.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X] I have verified that new and existing unit tests pass locally with my changes
- [X] I have not allowed coverage numbers to degenerate
- [X] I have maintained at least 90% code coverage
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Unit test and Integration test

### CODE REVIEW

**Comment by adarsh-dell** [comment]
Hi @AnikaAgiwal2711 , Can I get to know the % of code coverage? Also I can see that there are many UTs that are commented, Do we really need them? If NOT, can we delete those unnecessary lines of codes.

Please have a look at Checklist.
Thanks 
Adarsh

**Comment by AnikaAgiwal2711** [comment]
image

**Comment by AnikaAgiwal2711** [comment]
I'll remove the commented code. Thanks

**Comment by adarsh-dell** [comment]
Thanks @AnikaAgiwal2711, Would it be possible to increase the coverage >= 90%. And what was the coverage % before this change? If it was less than the current coverage then I am fine.

**Comment by AnikaAgiwal2711** [comment]
Increased the code coverage 
image

**Review by adarsh-dell — APPROVED** [review]
LGTM.
Thank @AnikaAgiwal2711 for addressing all comments.

**Review by AkshaySainiDell — APPROVED** [review]

**Pull request merged**
